version: "3.8"

networks:
  dataline:
    driver: bridge

volumes:
  dataline_dev:

services:
  backend:
    build:
      context: .
      target: dev
    ports:
      - "7377:7377"
    volumes:
      - dataline_dev:/home/.dataline  # persist local sqlite db
      - ./text2sql-backend/dataline:/home/dataline/backend/dataline
    networks:
      - dataline

  frontend:
    build:
      context: ./text2sql-frontend
    depends_on:
      - backend
    ports:
      - "5173:5173"
    volumes:
      - ./text2sql-frontend:/app
    networks:
      - dataline
