version: "3.8"

networks:
  dataline:
    driver: bridge

volumes:
  dataline_dev:

services:
  backend:
    build:
      context: .
      target: dev
    ports:
      - "7377:7377"
    volumes:
      - dataline_dev:/home/.dataline # persist local sqlite db
      # map local to remote folder, exclude venv
      - ./text2sql-backend:/home/dataline/backend
      - /home/dataline/backend/venv
    networks:
      - dataline

  frontend:
    build:
      context: ./text2sql-frontend
    depends_on:
      - backend
    ports:
      - "5173:5173"
    volumes:
      # map local to remote folder, exclude node_modules
      - ./text2sql-frontend:/app
      - /app/node_modules
    networks:
      - dataline
